# if not interactive shell
[[ $- != *i* ]] && return

# General
bindkey -e
zstyle :compinstall filename '/home/chiyonn/.zshrc'
autoload -Uz compinit
compinit

### Aliases
ALIASES_FILE=$HOME/.aliases
if [ -f "$ALIASES_FILE" ]; then
    source "$ALIASES_FILE"
fi

### History
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=10000

### Git
autoload -Uz vcs_info
precmd() { vcs_info }

zstyle ':vcs_info:git:*' formats '(%b)'
zstyle ':vcs_info:*' enable git

setopt PROMPT_SUBST

PS1=' 👻%F{white}%n%F{grey}@%m%f:%F{blue}%~%f %F{yellow}${vcs_info_msg_0_}%f%F{green}%%%f '
RPS1='%F{cyan}[%*]%f'

# Completion
fpath=(~/.zsh $fpath)
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

# Sync Check
DOTS_REPO_DIRPATH=$HOME/Projects/Dotty-McDotface
if [ -d "$DOTS_REPO_DIRPATH" ]; then
    source "$DOTS_REPO_DIRPATH/git_sync_check.sh"
fi

### Sway
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    exec sway
fi

# Open in tmux session (must be last)
if command -v tmux >/dev/null 2>&1; then
  if [ -z "$TMUX" ]; then
    ~/.config/tmux/tmux-dashboard-layout.sh
  fi
fi

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

eval "$(mise activate zsh)"

