# if not interactive shell
[[ $- != *i* ]] && return

# General
bindkey -e
zstyle :compinstall filename '/home/chiyonn/.zshrc'
autoload -Uz compinit
compinit

### Aliases
ALIASES_FILE=$HOME/.aliases
if [ -f "$ALIASES_FILE" ]; then
    source "$ALIASES_FILE"
fi

### History
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=10000

### Git
autoload -Uz vcs_info
precmd() { vcs_info }

zstyle ':vcs_info:git:*' formats '(%b)'
zstyle ':vcs_info:*' enable git

setopt PROMPT_SUBST

PS1=' 👻%F{white}%n%F{grey}@%m%f:%F{blue}%~%f %F{yellow}${vcs_info_msg_0_}%f%F{green}%%%f '
RPS1='%F{cyan}[%*]%f'

# Completion
fpath=(~/.zsh $fpath)
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash

# Sync Check
DOTS_REPO_DIRPATH=$HOME/Projects/Dotty-McDotface
if [ -d "$DOTS_REPO_DIRPATH" ]; then
    source "$DOTS_REPO_DIRPATH/git_sync_check.sh"
fi

### Sway
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    exec sway
fi

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_CURRENT_SESSION=sway
export LIBSEAT_BACKEND=logind
export QT_QPA_PLATFORM=wayland
export GDK_DPI_SCALE=1.5
export QT_SCALE_FACTOR=1.5
export MOZ_ENABLE_WAYLAND=1
export WINIT_UNIX_BACKEND=x11

### NodeJS 
export PATH="$HOME/.npm-global/bin:$PATH"

### Go
export PATH=$PATH:$(go env GOPATH)/bin
