modmap:
  - name: HHKB
    device: { only: ["HHKB-Hybrid_1 Keyboard"] }
    remap:
      rightshift: backspace

  - name: ThinkPad
    device: { only: ["AT Translated Set 2 keyboard"] }
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace

  - name: MD770
    device: { only: ["USB-HID Keyboard"] }
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace

keymap:
  - name: "Map Win + hjkl to arrow keys"
    remap:
      Super-h: left
      Super-j: down
      Super-k: up
      Super-l: right
