modmap:
  - name: HHKB
    device: { only: ["HHKB-Hybrid_1 Keyboard"] }
    remap:
      rightshift: backspace

  - name: ThinkPad
    device: { only: ["AT Translated Set 2 keyboard"] }
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace

  - name: MD770
    device: { only: ["USB-HID Keyboard"] }   # ← event5/9 と一致する名前だけ
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace
