modmap:
  - name: "ThinkPad Keyboard"
    device:
      only: "AT Translated Set 2 keyboard"
    grab: false
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace

keymap:
  - name: "Map Win + hjkl to arrow keys"
    remap:
      Super-h: left
      Super-j: down
      Super-k: up
      Super-l: right
