modmap:
    - name: "ThinkPad Keyboard"
      device:
        only: "AT Translated Set 2 keyboard"
      remap:
          KEY_CAPSLOCK: KEY_LEFTCTRL
          KEY_RIGHTSHIFT: KEY_BACKSPACE
          KEY_BACKSPACE: KEY_BACKSLASH
          KEY_BACKSLASH: KEY_BACKSPACE
