modmap:
  - name: "ThinkPad Keyboard"
    device:
      only: "AT Translated Set 2 keyboard"
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace

  - name: "MD-770 Keyboard"
    device:
      only: "USB-HID Keyboard"
    remap:
      capslock: leftctrl
      rightshift: backspace
      backspace: backslash
      backslash: backspace

keymap:
  - name: "Map Win + hjkl to arrow keys"
    remap:
      Super-h: left
      Super-j: down
      Super-k: up
      Super-l: right
